[package]
name = "rustchi-terminal"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]
path = "src/terminal.rs"

[dependencies]
rustchi-core = { path = "../rustchi-core" }
ansi_term = "0.12.1"
clap = { version = "4.3.4", features = ["derive"] }
itertools = "0.10.5"
