[package]
name = "rustchi-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]
path = "src/core.rs"

[dependencies]
automod = "1.0.8"
bitflags = "2.3.1"
bitmatch = "0.1.1"
tap = "1.0.1"
